server:
  port: 9090
logging:
  level:
    work.shrink.portupdater2: info
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/my_default?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
